import ServiceLandingPage from "@/components/content/ServiceLandingPage";
import { createPageMetadata } from "@/lib/seo";
export const metadata = createPageMetadata({ path: "/webdesign", title: "Webdesign für professionelle Unternehmenswebsites | Codavo", description: "Individuelle Unternehmenswebsites für Vertrauen, qualifizierte Anfragen und Sichtbarkeit bei Suchmaschinen und KI-Systemen." });
const faqs = [
  { q: "Was ist professionelles Webdesign?", a: "Professionelles Webdesign verbindet Gestaltung, Nutzerführung, Inhalte, Technik und Sichtbarkeit. Die Website soll Vertrauen schaffen, mobil funktionieren und gezielt zur Anfrage führen." },
  { q: "Wie entsteht der Projektumfang für eine neue Website?", a: "Der sinnvolle Umfang ergibt sich aus Projektziel, Seitenstruktur, Inhalten, Funktionen und den Anforderungen an die spätere Weiterentwicklung. Im Erstgespräch klären wir zuerst die Ausgangslage und entwickeln daraus ein passendes Angebot." },
  { q: "Warum ist individuelles Webdesign teurer als ein Baukasten?", a: "Individuelles Webdesign umfasst Strategie, UX/UI, Entwicklung, Content-Struktur, Performance und Qualitätssicherung statt einer reinen Template-Anpassung." },
  { q: "Ist Webdesign auch für KI-Systeme relevant?", a: "Ja. Klare Leistungsseiten, präzise Antworten, interne Links und strukturierte Daten helfen KI-Systemen bei der Einordnung." },
  { q: "Was ist der Unterschied zwischen Webdesign und Entwicklung?", a: "Webdesign definiert Struktur, Nutzerführung und Gestaltung. Entwicklung setzt diese Grundlage technisch und performant um." },
  { q: "Wie lange dauert eine professionelle Website?", a: "Die Dauer hängt von Umfang, Inhalten und Funktionen ab. Nach dem Erstgespräch kann Codavo einen realistischen Zeitplan nennen." },
  { q: "Kann eine Website später erweitert werden?", a: "Ja. Individuelle Entwicklung ermöglicht spätere Landingpages, Funnel, Schnittstellen und Web-App-Funktionen." },
  { q: "Warum ist eine Website für die Kundengewinnung wichtig?", a: "Sie beeinflusst Auffindbarkeit, ersten Eindruck und Kontaktentscheidung. Klare Inhalte und Nutzerwege können qualifizierte Anfragen unterstützen." },
  { q: "Kann Tracking in die Unternehmenswebsite integriert werden?", a: "Ja. Im Growth- oder Enterprise-Umfang kann ein Tracking-Grundsetup für wichtige Website-Ereignisse integriert werden, passend zur Einwilligungslogik und zum Projektziel. Welche Tools sinnvoll sind, wird nach Bedarf festgelegt." },
];
export default function Page() { return <ServiceLandingPage path="/webdesign" eyebrow="Unternehmenswebsite · UX/UI · Sichtbarkeit" h1="Webdesign für professionelle Unternehmenswebsites" intro="Codavo entwickelt individuelle Unternehmenswebsites für Unternehmen, die professionell auftreten, bei Suchmaschinen und KI-Systemen gefunden werden und qualifizierte Anfragen unterstützen möchten." directAnswer="Professionelles Webdesign verbindet Positionierung, Nutzerführung, Gestaltung, Technik und Sichtbarkeit zu einer Website, die Vertrauen schafft und Leistungen verständlich erklärt." serviceName="Professionelles Webdesign" serviceDescription="Individuelle Unternehmenswebsites mit UX/UI, moderner Entwicklung und SEO-, AEO- und LLMO-Struktur." sections={[
  { title: "Wann professionelles Webdesign sinnvoll ist", text: "Wenn der bestehende Auftritt nicht zur Qualität des Unternehmens passt, Leistungen unklar bleiben oder die technische Grundlage zukünftige Schritte begrenzt." },
  { title: "Mehr als Gestaltung", text: "Positionierung, Informationsarchitektur, Inhalte, Anfragewege und technische Qualität bestimmen gemeinsam, ob die Website ihre Aufgabe erfüllt." },
  { title: "Individuell statt standardisiert", text: "Eigener Code ermöglicht mehr Kontrolle über Design, Performance, semantische Struktur und spätere Erweiterungen." },
  { title: "Sichtbarkeit bei Google und KI", text: "Leistungsseiten, Direktantworten, interne Links, Metadaten und strukturierte Daten unterstützen Google, AI Overviews, ChatGPT, Gemini und weitere Systeme bei der Einordnung." },
  { title: "Was eine moderne Website braucht", text: "Klare Botschaften, mobile Nutzerführung, schnelle Ladezeiten, Vertrauenssignale, verständliche Leistungen und eindeutige Kontaktwege." },
  { title: "Individuell geplanter Projektumfang", text: "Seiten, Inhalte und Funktionen werden nicht in ein starres Paket gepresst, sondern passend zu Zielgruppe, Anfrageweg und Weiterentwicklung geplant." },
]} relatedLinks={[{ href: "/landingpage-erstellen-lassen", label: "Landingpage", description: "Fokussierte Seiten für Angebote und Kampagnen." },{ href: "/funnel-erstellen-lassen", label: "Funnel-System", description: "Mehrstufige Wege zur Anfrage." },{ href: "/wissen/seo-aeo-llmo", label: "SEO, AEO und LLMO", description: "Moderne Sichtbarkeit verstehen." }]} beforeFaq={<section className="section section--quiet"><div className="container max-w-6xl"><p className="eyebrow">Arbeitsweise</p><h2 className="section-title mt-5 text-white">Qualität entsteht nicht zufällig</h2><div className="mt-10 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{["Ziele und Anforderungen sauber klären", "Informationsarchitektur und Nutzerführung planen", "Individuelles UX/UI statt Standardvorlagen", "Performance und mobile Darstellung prüfen", "SEO-, AEO- und LLMO-Grundlagen berücksichtigen", "Qualitätssicherung vor dem Launch", "Technische Betreuung und Weiterentwicklung einplanen"].map((item) => (<div key={item} className="rounded-2xl border border-white/8 bg-white/[0.025] p-5 text-sm leading-7 text-slate-300">{item}</div>))}</div></div></section>} faqs={faqs} />; }
