import ServiceLandingPage from "@/components/content/ServiceLandingPage";
import { createPageMetadata } from "@/lib/seo";
export const metadata = createPageMetadata({ path: "/webdesign", title: "Webdesign für professionelle Unternehmenswebsites | Codavo", description: "Individuelle Unternehmenswebsites für Vertrauen, qualifizierte Anfragen und Sichtbarkeit bei Suchmaschinen und KI-Systemen." });
const faqs = [
  { q: "Was ist professionelles Webdesign?", a: "Professionelles Webdesign verbindet Gestaltung, Nutzerführung, Inhalte, Technik und Sichtbarkeit. Die Website soll Vertrauen schaffen, mobil funktionieren und gezielt zur Anfrage führen." },
  { q: "Was kostet Webdesign bei Codavo?", a: "Webdesign-Projekte starten im Launch-Paket ab 4.900 €. Growth startet ab 7.900 €. Der finale Preis hängt von Seiten, Funktionen und Projektziel ab." },
  { q: "Warum ist individuelles Webdesign teurer als ein Baukasten?", a: "Individuelles Webdesign umfasst Strategie, UX/UI, Entwicklung, Content-Struktur, Performance und Qualitätssicherung statt einer reinen Template-Anpassung." },
  { q: "Ist Webdesign auch für KI-Systeme relevant?", a: "Ja. Klare Leistungsseiten, präzise Antworten, interne Links und strukturierte Daten helfen KI-Systemen bei der Einordnung." },
  { q: "Was ist der Unterschied zwischen Webdesign und Entwicklung?", a: "Webdesign definiert Struktur, Nutzerführung und Gestaltung. Entwicklung setzt diese Grundlage technisch und performant um." },
  { q: "Wie lange dauert eine professionelle Website?", a: "Die Dauer hängt von Umfang, Inhalten und Funktionen ab. Nach dem Erstgespräch kann Codavo einen realistischen Zeitplan nennen." },
  { q: "Kann eine Website später erweitert werden?", a: "Ja. Individuelle Entwicklung ermöglicht spätere Landingpages, Funnel, Schnittstellen und Web-App-Funktionen." },
  { q: "Warum ist eine Website für die Kundengewinnung wichtig?", a: "Sie beeinflusst Auffindbarkeit, ersten Eindruck und Kontaktentscheidung. Klare Inhalte und Nutzerwege können qualifizierte Anfragen unterstützen." },
];
export default function Page() { return <ServiceLandingPage path="/webdesign" eyebrow="Unternehmenswebsite · UX/UI · Sichtbarkeit" h1="Webdesign für professionelle Unternehmenswebsites" intro="Codavo entwickelt individuelle Unternehmenswebsites für Unternehmen, die professionell auftreten, bei Suchmaschinen und KI-Systemen gefunden werden und qualifizierte Anfragen unterstützen möchten." directAnswer="Professionelles Webdesign verbindet Positionierung, Nutzerführung, Gestaltung, Technik und Sichtbarkeit zu einer Website, die Vertrauen schafft und Leistungen verständlich erklärt." serviceName="Professionelles Webdesign" serviceDescription="Individuelle Unternehmenswebsites mit UX/UI, moderner Entwicklung und SEO-, AEO- und LLMO-Struktur." sections={[
  { title: "Wann professionelles Webdesign sinnvoll ist", text: "Wenn der bestehende Auftritt nicht zur Qualität des Unternehmens passt, Leistungen unklar bleiben oder die technische Grundlage zukünftige Schritte begrenzt." },
  { title: "Mehr als Gestaltung", text: "Positionierung, Informationsarchitektur, Inhalte, Anfragewege und technische Qualität bestimmen gemeinsam, ob die Website ihre Aufgabe erfüllt." },
  { title: "Individuell statt standardisiert", text: "Eigener Code ermöglicht mehr Kontrolle über Design, Performance, semantische Struktur und spätere Erweiterungen." },
  { title: "Sichtbarkeit bei Google und KI", text: "Leistungsseiten, Direktantworten, interne Links, Metadaten und strukturierte Daten unterstützen Google, AI Overviews, ChatGPT, Gemini und weitere Systeme bei der Einordnung." },
  { title: "Was eine moderne Website braucht", text: "Klare Botschaften, mobile Nutzerführung, schnelle Ladezeiten, Vertrauenssignale, verständliche Leistungen und eindeutige Kontaktwege." },
  { title: "Drei Projektstufen", text: "Launch startet ab 4.900 €, Growth ab 7.900 € und Growth Plus ab 14.900 €. Der passende Umfang richtet sich nach Ziel und Funktionen." },
]} relatedLinks={[{ href: "/landingpage-erstellen-lassen", label: "Landingpage", description: "Fokussierte Seiten für Angebote und Kampagnen." },{ href: "/funnel-erstellen-lassen", label: "Funnel-System", description: "Mehrstufige Wege zur Anfrage." },{ href: "/wissen/seo-aeo-llmo", label: "SEO, AEO und LLMO", description: "Moderne Sichtbarkeit verstehen." }]} faqs={faqs} />; }
