import Link from "next/link";
import Footer from "@/components/Footer";
import { createPageMetadata } from "@/lib/seo";
export const metadata = createPageMetadata({ path: "/leistungen", title: "Leistungen für professionelle Unternehmenswebsites | Codavo", description: "Unternehmenswebsites, Landingpages, Funnel, Web-Apps, individuelle Software sowie Hosting und Wartung." });
const groups = [
  { title: "Professionelle Unternehmenswebsites", text: "Das Hauptangebot für Unternehmen, die Vertrauen schaffen, Leistungen klar darstellen und bei Suchmaschinen sowie KI-Systemen besser verstanden werden möchten.", links: [["/webdesign", "Webdesign"], ["/standorte/stuttgart", "Webdesign Stuttgart"]] },
  { title: "Landingpages und Funnel", text: "Vertriebsorientierte Erweiterungen für Kampagnen, konkrete Angebote, Anfragen, Termine oder Bewerbungen.", links: [["/landingpage-erstellen-lassen", "Landingpage erstellen lassen"], ["/funnel-erstellen-lassen", "Funnel erstellen lassen"]] },
  { title: "Web-Apps und Software", text: "Weiterführende digitale Lösungen für Portale, Dashboards, interne Tools, Schnittstellen und individuelle Prozesse.", links: [["/web-app-entwicklung", "Web-App Entwicklung"], ["/softwareloesungen-fuer-kmu", "Softwarelösungen für KMU"], ["/digitale-systeme", "Digitale Systeme"]] },
  { title: "Hosting und Wartung", text: "Laufende technische Betreuung, Updates und Weiterentwicklung nach dem Launch.", links: [["/hosting-wartung", "Hosting & Wartung"], ["/website-check", "Bestehende Website prüfen"]] },
] as const;
export default function Page() { return <><main className="min-h-screen pt-24"><section className="section text-center"><div className="container max-w-4xl"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-indigo-300">Codavo Leistungen</p><h1 className="mt-4 text-4xl font-semibold text-white md:text-6xl">Digitale Leistungen mit der Unternehmenswebsite im Mittelpunkt</h1><p className="mx-auto mt-6 max-w-3xl text-lg leading-8 text-slate-300">Codavo entwickelt professionelle Websites als Grundlage und ergänzt sie bei Bedarf um Landingpages, Funnel, Web-Apps, Software und laufende Betreuung.</p></div></section><section className="section section--alt"><div className="container max-w-5xl grid gap-5 md:grid-cols-2">{groups.map((group) => <article key={group.title} className="card"><h2 className="text-2xl font-semibold text-white">{group.title}</h2><p className="mt-3 leading-7 text-slate-300">{group.text}</p><div className="mt-5 flex flex-wrap gap-2">{group.links.map(([href,label]) => <Link key={href} href={href} className="rounded-full border border-white/20 px-4 py-2 text-sm text-indigo-200 hover:bg-white/10">{label}</Link>)}</div></article>)}</div></section><section className="section"><div className="container max-w-4xl text-center"><h2 className="text-3xl font-semibold text-white">Welche Leistung passt zu Ihrem Ziel?</h2><p className="mt-4 text-slate-300">Im Erstgespräch klären wir, ob eine neue Website, eine fokussierte Landingpage oder eine weiterführende digitale Lösung sinnvoll ist.</p><Link href="/kontakt" data-track-event="cta_contact_click" data-track-label="Leistungen Abschluss" className="mt-7 inline-flex rounded-full bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500 px-5 py-3 font-medium text-white">Kostenloses Erstgespräch vereinbaren</Link></div></section></main><Footer /></>; }
